### ISSUE TITLE
Wondering about the Accept header

### ISSUE THREAD

**Issue by halfluke** [dolevf/graphql-cop#16]
Hi Doleh,

do you think graphql-cop should use the Accept: application/json header by default instead of \*/\* ?
As I mentioned previously, the environment where I tested would immediately error out if the Accept header was not application/json.

Additionally, have you noticed that running it against DVGA does not return the GraphiQL playground finding unless Accept is set to text/html ?
We can override the header with -H, but I was thinking of setting it by default in the info_graphiql.py check.
Two lines of codes for a PR: one before the check to set it and one before the end to remove it, if you want :)

**Comment by dolevf** [comment]
Yeah - graphql playground and GraphiQL respond differently to GET requests. The accept header seems to only be required in GraphiQL as opposed to the Playground. I merged your PR to resolve this.
