### ISSUE TITLE
Failing to find GraphQL

### ISSUE THREAD

**Issue by T3rm1nal23** [dolevf/graphql-cop#21]
The following code at line 87:
```
for path in paths:
    if not is_graphql(path, proxy, HEADERS):
        print(path, 'does not seem to be running GraphQL.')
        continue
    for test in tests:
        json_output.append(test(path, proxy, HEADERS))
```
Is not finding graphql endpoints that are clearly present.

![Screenshot 2022-11-01 092015](https://user-images.githubusercontent.com/70535509/199269694-53a0bcd2-e8be-4f47-8ddf-0c9d3921a854.png)

![Screenshot 2022-11-01 091729](https://user-images.githubusercontent.com/70535509/199269085-c4cecf26-2da7-436b-bed9-f4c4ff7fae0c.png)

If I comment out the if not is_graphql statement and run the tests, the tests are successful.

![image](https://user-images.githubusercontent.com/70535509/199271057-a8bfb5ef-b267-43ba-b5a8-54c8597358ad.png)

![Screenshot 2022-11-01 092305](https://user-images.githubusercontent.com/70535509/199270778-d481a456-443e-4643-ae43-6189d43e1b16.png)

**Comment by dolevf** [comment]
That's an interesting typename for sure. :)

**Comment by T3rm1nal23** [comment]
I'm not sure, this was just for an engagement I'm doing right now.  I think a force tests option would probably be the way to go for situations where graphql is known to be running on the server.

**Comment by dolevf** [comment]
That's a good idea, I can put up a PR for this
