### ISSUE TITLE
Unable to use tool error this error occurs

### ISSUE THREAD

**Issue by zenython** [dolevf/graphql-cop#35]
Traceback (most recent call last):
  File "/home/user/tools/graphql-cop/graphql-cop.py", line 11, in <module>
    from lib.tests.info_field_suggestions import field_suggestions
  File "/home/user/tools/graphql-cop/lib/tests/info_field_suggestions.py", line 2, in <module>
    from lib.utils import graph_query, get_error, curlify
  File "/home/user/tools/graphql-cop/lib/utils.py", line 168
    '''
        ^
SyntaxError: f-string: expecting '}'

**Comment by jankoksik** [comment]
Hi,
Issue is with the new realese or new updated version?

**Comment by jankoksik** [comment]
@zenython I can't reproduce the error :( 
Can you provide more information? 
python version? command you used ?
I will try to fix this error as fast as possible for you.

**Comment by zenython** [comment]
i think its because of the way of writing syntax in utils.py", line 168 the script is expecting  " } "

**Comment by zenython** [comment]
python version : Python 3.11.9
and all the requirement latest versions
command used :-  python3 graphql-cop.py -h
![image](https://github.com/user-attachments/assets/ad2f3166-2d8e-46a7-a2b5-c12c44229c83)

**Comment by jankoksik** [comment]
> i think its because of the way of writing syntax in utils.py", line 168 the script is expecting " } "

yea but its one line if in f string  { } section so it shouldnt be an issue

**Comment by jankoksik** [comment]
@zenython try updating python to 3.12.0.
I see in the python documentation that they changed something with fstings in this versions.
In my free time i will try to make code more universal :(

**Comment by jankoksik** [comment]
please let me know if it would work

**Comment by dolevf** [comment]
I've reverted graphql cop to pre-html reporting feature for now. The tool needs to support not only 3.12

**Comment by jankoksik** [comment]
There was an issue with fstrings with previous versions of python. I am finishing fix for this :)

**Comment by zenython** [comment]
Thanks for the fast response and efforts ! 🙏

**Comment by jankoksik** [comment]
No problem ;)
The fix is ready and waiting in the pull request section.
I would appreciate the review :D

**Comment by zenython** [comment]
ok lemme see !

**Comment by zenython** [comment]
yes it works now, great thankyou for the efforts 👍❤️

**Comment by jankoksik** [comment]
No problem 🫡
Thanks for checking and i hope you will enjoy the changes 😁

**Comment by zenython** [comment]
there is a problem again 🥲

**Comment by zenython** [comment]
**now this time when is use -f the application crashes**
![image](https://github.com/user-attachments/assets/3af6a146-d18b-4fb7-8c40-bd8205fa3013)

**as well as while doing normal query it works good but when i add proxy it says it doesn't have  any graphql endpoint** 
**without proxy :-** 
![image](https://github.com/user-attachments/assets/297b17cc-dcaf-4981-a399-a305438cd729)
**with proxy :-** 
![image](https://github.com/user-attachments/assets/0a0dc1e9-a03d-4eb8-9a3e-53d826130d4f)
**and when i use force this error occurs :-** 
![image](https://github.com/user-attachments/assets/94a732f8-d9c5-4820-b95e-170c0e7c262c)

**Comment by jankoksik** [comment]
Hmmm let me check

**Comment by jankoksik** [comment]
its not a problem related to my part of the code so i will need some time to analyze

**Comment by jankoksik** [comment]
can you check for me if this code will work? 
```python 
def curlify(obj):
  req = obj['request']
  command = "curl -X {method} -H {headers} -d '{data}' '{uri}'"
  method = req['method']
  uri = req["url"]
  if req["body"]:
    try:
      data = req["body"].decode('UTF-8')
    except:
      reqb = bytes(req["body"], 'UTF-8')
      data = reqb.decode('UTF-8')
  else:
    data = ''
  headers = ['"{0}: {1}"'.format(k, v) for k, v in req["headers"].items()]
  headers = " -H ".join(headers)
  return command.format(method=method, headers=headers, data=data, uri=uri)
```
please let me know

**Comment by jankoksik** [comment]
Does the issue occur on the 1.12 version as well?

**Comment by jankoksik** [comment]
@zenython Soooooo i rly tried to reproduce your errors so in my fork i created a massive github actions that tests code from python 3.7 to 3.12 and i still cant reproduce it 🙁

**Comment by zenython** [comment]
sorry there i was out of the town ! wait a sec i will check again

**Comment by zenython** [comment]
still the error occurs! 🥲

**Comment by jankoksik** [comment]
hmmm, I guess you are using burp as your proxy. 
I am thinking how we can debug it on your side so we know what crashes the app.
Can you check if there is also a problem with 1.12 realese?

**Comment by zenython** [comment]
yes ! btw you haven't pushed the updated code !?

**Comment by zenython** [comment]
i this there is a problem with curlify while handling the directories properly
![image](https://github.com/user-attachments/assets/571d16cf-3288-424c-972c-04a908c199c8)

**Comment by jankoksik** [comment]
can you try changing curlify from utils.py to this code and check it for me ? : 
```python
def curlify(obj):
  req = obj['request']
  command = "curl -X {method} -H {headers} -d '{data}' '{uri}'"
  method = req['method']
  uri = req["url"]
  if req["body"]:
    try:
      data = req["body"].decode('UTF-8')
    except:
      reqb = bytes(req["body"], 'UTF-8')
      data = reqb.decode('UTF-8')
  else:
    data = ''
  headers = ['"{0}: {1}"'.format(k, v) for k, v in req["headers"].items()]
  headers = " -H ".join(headers)
  return command.format(method=method, headers=headers, data=data, uri=uri)
```

**Comment by zenython** [comment]
okay lemme check

**Comment by jankoksik** [comment]
any updates? :D

**Comment by zenython** [comment]
no still the error occours !

**Comment by jankoksik** [comment]
And can you provide the output?
There was a print of object before entering the code further.
Is it empty? If so then smth went wrong earlier.

**Comment by jankoksik** [comment]
No matter how hard i try i cant reproduce those errors...
```
> python .\graphql-cop.py -t [...] --proxy=http://127.0.0.1:8080 -f
Running a forced scan against the endpoint /graphiql
Running a forced scan against the endpoint /playground
Running a forced scan against the endpoint /console
Running a forced scan against the endpoint /graphql
```
Burp is correctly used as a proxy.
![obraz](https://github.com/user-attachments/assets/c5101da6-e733-45ae-b64f-6d9014cc1052)

im sorry :(

**Comment by zenython** [comment]
i think python version is creating problem in my pc

**Comment by jankoksik** [comment]
Well it can be but i am testing different versions using github actions.
Maybe venv broke?
Do you have docker to try to run it?
I will write dockerfile for you when i will be home :)
