### ISSUE TITLE
Doesn't run graphql-cop.py

### ISSUE THREAD

**Issue by bsonmez** [dolevf/graphql-cop#8]
I tried several times both on local and real URLs but did not succeed. The error is like the following. 

Ps: the project is on and lives in port 1003.

```
x@Mac graphql-cop % python3 graphql-cop.py -t http://192.168.1.2:1003/graphql
Traceback (most recent call last):
  File "/path/to/folder/graphql-cop/graphql-cop.py", line 64, in <module>
    if field_suggestions(url, proxy, HEADERS):
TypeError: field_suggestions() takes 1 positional argument but 3 were given
```

**Comment by 123Pro123Pro** [comment]
Same issue!

**Comment by 123Pro123Pro** [comment]
I just modify the python files in graphql-cop\lib\tests by adding  proxy, HEADERS  to params of function field_suggestions :

```

def field_suggestions(url, proxy, HEADERS):
  """Retrieve field suggestions."""
  result = False

  q = 'query { __schema { directive } }'    
  gql_response = graph_query(url, proxy, HEADERS, payload=q)
    
  try:
    if 'Did you mean' in get_error(gql_response):
      result = True
  except:
    pass
  
  return result

```
And repeat that with function alias_overloading, batch_query, directive_overloading, field_duplication, field_suggestions, get_method_support, detect_graphiql, introspection, trace_mode

Then the code will run well :D
