### ISSUE TITLE
No module Found Error

### ISSUE THREAD

**Issue by moolakarapaiyan** [dolevf/graphql-cop#9]
I tried to run python graphql-cop.py , but it throws error like this

Traceback (most recent call last):
  File "graphql-cop.py", line 9, in <module>
    from lib.tests.info_field_suggestions import field_suggestions
ModuleNotFoundError: No module named 'lib.tests'

**Comment by atikh** [comment]
Check if The issue got resolved by placing an empty __init__.py file in the folder.

**Comment by dolevf** [comment]
Can you pull the latest copy and see if you run into the same issue?

**Comment by Lsploit** [comment]
Pulled the latest copy. The issue persists.

**Comment by dolevf** [comment]
Can you copy and paste the steps you took and the output? 

Also, are you using Python3?

**Comment by dolevf** [comment]
Hi,

I'm closing this for now. Please reopen as soon as you have more information so I can help you address the errors.

**Comment by Lsploit** [comment]
` git clone https://github.com/dolevf/graphql-cop.git
# cd graphql-cop/
# ls
config.py  graphql-cop.py  lib  LICENSE  README.md  requirements.txt  version.py
`#` python graphql-cop.py -h
Traceback (most recent call last):
  File "graphql-cop.py", line 10, in <module>
    from lib.tests.info_field_suggestions import field_suggestions
ModuleNotFoundError: No module named 'lib.tests'
`

**Comment by Lsploit** [comment]
git clone https://github.com/dolevf/graphql-cop.git
# cd graphql-cop/
# ls
config.py  graphql-cop.py  lib  LICENSE  README.md  requirements.txt  version.py
`#` python graphql-cop.py -h
Traceback (most recent call last):
  File "graphql-cop.py", line 10, in <module>
    from lib.tests.info_field_suggestions import field_suggestions
ModuleNotFoundError: No module named 'lib.tests'
